spring:
  application:
    name: microservice-api-gateway-zuul
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone=: http://localhost:8761/eureka

zuul:
  routes:
    worker:
      service-id: microservice-worker
      path: /microservice-worker/**
    payroll:
      service-id: microservice-payroll
      path: /microservice-payroll/**
    user:
      service-id: microservice-user
      path: /microservice-user/**
    oauth:
      service-id: microservice-oauth
      path: /microservice-oauth/**
      sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
