spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:h2:mem:db_microservice
    username: username
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.name:${random.value}}
