spring:
  application:
    name: microservice-worker
  datasource:
    url: jdbc:h2:mem:db_worker
    username: username_db_worker
    password: password_db_worker
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8001
